### ISSUE TITLE
how to quickly preview project

### ISSUE THREAD

**Issue by simevo** [sindastra/CPPaste4#6]
[in case you want to add this to README]
tested on a clean Debian 10 (Buster):
```
apt install git php
git clone https://github.com/sindastra/CPPaste4
cd CPPaste4/src/www/
cp inc.config.sample.php inc.config.php 
php -S 0.0.0.0:8000
```

then visit:  http://localhost:8000/
it works !

**Comment by sindastra** [comment]
I would recommend changing that to php-cli so that it won't install any unwanted web server.
Did you know, renaming the config is not needed just for testing?
I will update the README.md now.

**Comment by simevo** [comment]
I confirm that the instructions also works with `php-cli` instead of `php`

**Comment by sindastra** [comment]
I adapted your instructions and added them to the README.md now.
Other than what I already mentioned I changed the git URL.
Furthermore, for security reasons, I changed the listen IP to localhost.
Feedback appreciated!
