### ISSUE TITLE
accurately pitch your project

### ISSUE THREAD

**Issue by simevo** [sindastra/CPPaste4#7]
the one-liner that describes the project is important for people who stumble upon it, they want to know if this serves their needs

building upon the current "_CPPaste4 is a minimalistic web-app used to store and share code pastes! It runs in modern browsers but also in old ones like IE8 lol._", I think you should also highlight key features:
- requires no DB
- saves pastes as plain files
- (almost) zero-config
- no PHP dependencies (only core PHP)
- no JavaScript

not sure which of those belong to the pitch and which to the README tho

**Comment by sindastra** [comment]
That's a good suggestion! I should definitely add those.

Do you happen to have a suggestion for the one-liner?

What do you think about these following points?
 - zero-config (config optional)
 - easy deployment to web host
 - wide range of browser support

**Comment by sindastra** [comment]
Added a feature list. Feedback appreciated.

**Comment by simevo** [comment]
LGTM
